-- PostgreSQL schema generated from current Sequelize models
-- Project: Smart Food Security Platform

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_users_role') THEN
    CREATE TYPE enum_users_role AS ENUM ('student', 'moderator', 'admin');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_food_listings_category') THEN
    CREATE TYPE enum_food_listings_category AS ENUM (
      'cooked-meal',
      'raw-ingredients',
      'snacks',
      'beverages',
      'baked-goods',
      'fruits-vegetables',
      'other'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_food_listings_status') THEN
    CREATE TYPE enum_food_listings_status AS ENUM ('available', 'reserved', 'claimed', 'expired');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_community_posts_type') THEN
    CREATE TYPE enum_community_posts_type AS ENUM ('tip', 'story', 'event', 'discussion');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_audit_logs_actor_role') THEN
    CREATE TYPE enum_audit_logs_actor_role AS ENUM ('student', 'moderator', 'admin');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  student_id VARCHAR(255) NOT NULL UNIQUE,
  avatar VARCHAR(255) NOT NULL DEFAULT '',
  bio TEXT NOT NULL DEFAULT '',
  impact_points INTEGER NOT NULL DEFAULT 0,
  meals_shared INTEGER NOT NULL DEFAULT 0,
  meals_received INTEGER NOT NULL DEFAULT 0,
  role enum_users_role NOT NULL DEFAULT 'student',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS food_listings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category enum_food_listings_category NOT NULL,
  quantity VARCHAR(255) NOT NULL,
  servings INTEGER NOT NULL DEFAULT 1,
  dietary_info TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  allergens VARCHAR(255) NOT NULL DEFAULT '',
  expires_at TIMESTAMPTZ NOT NULL,
  pickup_location VARCHAR(255) NOT NULL,
  pickup_instructions TEXT NOT NULL DEFAULT '',
  image_url VARCHAR(255) NOT NULL DEFAULT '',
  status enum_food_listings_status NOT NULL DEFAULT 'available',
  donor_id INTEGER NOT NULL,
  claimed_by_id INTEGER NULL,
  co2_saved DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_food_listings_donor
    FOREIGN KEY (donor_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_food_listings_claimed_by
    FOREIGN KEY (claimed_by_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS community_posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  type enum_community_posts_type NOT NULL DEFAULT 'discussion',
  likes INTEGER[] NOT NULL DEFAULT '{}'::INTEGER[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_community_posts_author
    FOREIGN KEY (author_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL,
  author_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comments_post
    FOREIGN KEY (post_id) REFERENCES community_posts(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_comments_author
    FOREIGN KEY (author_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS food_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  food_name VARCHAR(255) NOT NULL,
  location VARCHAR(255),
  status VARCHAR(255) NOT NULL DEFAULT 'pending',
  "userId" INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_food_requests_user
    FOREIGN KEY ("userId") REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message VARCHAR(255) NOT NULL,
  read BOOLEAN NOT NULL DEFAULT FALSE,
  "userId" INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_notifications_user
    FOREIGN KEY ("userId") REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "AuditLogs" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "actorId" INTEGER NOT NULL,
  "actorRole" enum_audit_logs_actor_role NOT NULL,
  action VARCHAR(255) NOT NULL,
  "targetType" VARCHAR(255) NOT NULL,
  "targetId" VARCHAR(255) NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_audit_logs_actor
    FOREIGN KEY ("actorId") REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_food_listings_donor_id ON food_listings(donor_id);
CREATE INDEX IF NOT EXISTS idx_food_listings_claimed_by_id ON food_listings(claimed_by_id);
CREATE INDEX IF NOT EXISTS idx_community_posts_author_id ON community_posts(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON comments(post_id);
CREATE INDEX IF NOT EXISTS idx_comments_author_id ON comments(author_id);
CREATE INDEX IF NOT EXISTS idx_food_requests_user_id ON food_requests("userId");
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications("userId");
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id ON "AuditLogs"("actorId");

COMMIT;
